### ISSUE TITLE
Они отключили поддержку предыдущих версий VK Api

### ISSUE THREAD

**Issue by PerchunPak** [alexanderlarin/aiovk#57]
```py
aiovk.exceptions.VkAPIError: ({'error_code': 8, 'error_msg': 'Invalid request: versions below 5.81 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates', 'request_params': [{'key': 'method', 'value': 'groups.getLongPollServer'}, {'key': 'oauth', 'value': '1'}, {'key': 'group_id', 'value': '206184278'}, {'key': 'v', 'value': '5.74'}]}, 'https://api.vk.com/method/groups.getLongPollServer')
```
Возникает при вызове `longpoll.wait()`

**Comment by alexanderlarin** [comment]
Я форкнул и переаплодил с фиксами https://pypi.org/project/aiovk2/ Попробуй

**Comment by Fahreeve** [comment]
ты вчера закрыл свой пр, я на новогодних хотел новый билд сделать, но у тебя в ветке тесты падали

**Comment by alexanderlarin** [comment]
@Fahreeve ну я закрыл его случайно, видимо. на праздниках или раньше они опять что-то поменяли на авторизации, я добавил еще пару правок. все версии до 5.81 они также задепрекейтили. тесты на pool кажется не работают теперь и до моего PR, а тесты с таймингами запросов, вообще говоря, мигающие, надо еще подумать как их переписать, можешь посмотреть мастер на моем гите

**Comment by alexanderlarin** [comment]
> ```python
> aiovk.exceptions.VkAPIError: ({'error_code': 8, 'error_msg': 'Invalid request: versions below 5.81 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates', 'request_params': [{'key': 'method', 'value': 'groups.getLongPollServer'}, {'key': 'oauth', 'value': '1'}, {'key': 'group_id', 'value': '206184278'}, {'key': 'v', 'value': '5.74'}]}, 'https://api.vk.com/method/groups.getLongPollServer')
> ```
> 
> Возникает при вызове `longpoll.wait()`

Исправлено в последней версии [https://github.com/alexanderlarin/aiovk/releases/tag/v4.1.0](v4.1.0)
